site_name: Pontis VBA Documentation
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
  palette:
    accent: light blue

  font:
    text: Geogrotesque
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
#  - git-revision-date
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/pontis-engineering
    - icon: material/web
      link: https://www.pontis-engineering.com
  generator: false

nav:
  - Home:
      - General information: index.md
  - Documentation:
    - pages/docs/index.md
    - Excel:
      - General: pages/docs/vba_xls_general.md
    - Femap:
      - General: pages/docs/vba_femap_general.md
      - Geometry: pages/docs/vba_femap_geometry.md
      - Materials : pages/docs/vba_femap_materials.md
      - Properties & Layups: pages/docs/vba_femap_property_en_layups.md


  - FAQ: pages/FAQ.md

extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/furmanp/Pontis-VBA
repo_name: GitHub
edit_uri: ""

markdown_extensions:
  - md_in_html
  - pymdownx.keys
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
